version: "3.9"
services:
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./.docker/volumes/database:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: .docker/ror/Dockerfile
    env_file:
      - .env
    volumes:
      - ./ror:/ror
    ports:
      - "3000:3000"
    depends_on:
      - database
  # clamav:
  #   image: clamav/clamav:stable_base
  #   command: "chmod 777 /var/run/clamav/"
  #   restart: always
  #   volumes:
  #     - ./.docker/volumes/clamav/run/:/var/run/clamav/
  #     - ./.docker/volumes/clamav/lib/:/var/lib/clamav/
  #   environment:
  #     - CLAMD_SETTINGS_CSV=LocalSocket=/var/run/clamav/clamd.ctl